unbind r # unbind tmux default reload key
bind r  source-file ~/.tmux.conf \; display "Reloaded!"

set  -g prefix C-s
set -g mouse on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

setw  -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#keybind customization
bind-key C-t new-session -s main

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'fabioluciano/tmux-tokyo-night'

# Session persistence
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
set -g @resurrect-capture-pane-contents 'on'

### Tokyo Night Theme configuration
#set -g @theme_variation 'moon'
#set -g @theme_left_separator ''
#set -g @theme_right_separator ''

set -g status-position top
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

run '~/.tmux/plugins/tpm/tpm'
