[/]
accent-color='purple'
color-scheme='prefer-dark'
cursor-size=24
cursor-theme='default'
gtk-im-module='ibus:xim'
gtk-theme='catppuccin-mocha-mauve-standard+default'
icon-theme='Adwaita'
toolkit-accessibility=false
